spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TestGoit
    username: postgres
    password: 02062006ur
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

#  mvc:
#   view:
#     prefix: /WEB-INF/jsp/
#     suffix: .jsp

myconfig:
  welcome:
    message: Hello user,