spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TestGoit
    username: postgres
    password: 02062006ur
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect